name: postgresql-and-timeout
description: Start PostgreSQL and increase timeout

runs:
  using: "composite"
  steps:
    - if: ${{ runner.os == 'Linux' }}
      run: |
        PGCONF="$(ls /etc/postgresql/*/main/pg_hba.conf)"
        sudo sed -i.bak -E "s/peer|scram-sha-256/trust/g" "$PGCONF"
        sudo service postgresql start
      shell: bash
    - if: ${{ runner.os == 'Windows' }}
      run: echo "$PGBIN" >> $GITHUB_PATH
      shell: bash
    - if: ${{ runner.os == 'macOS' }}
      run: echo "PGDATA=/usr/local/var/postgres" >> $GITHUB_ENV
      shell: bash
    - if: ${{ runner.os == 'macOS' }}
      run: pg_ctl -D "$PGDATA" initdb
      shell: bash
    - if: ${{ runner.os == 'Windows' || runner.os == 'macOS' }}
      run: pg_ctl -D "$PGDATA" -l "$PGDATA/server.log" start
      shell: bash
    - if: ${{ runner.os == 'macOS' }}
      run: createuser -s postgres
      shell: bash
    - run: echo "GOFLAGS=$GOFLAGS -timeout=30m" >> $GITHUB_ENV
      shell: bash
